exclude: docs|node_modules|migrations|.git|.tox
fail_fast: false

default_language_version:
  python: python3.13

default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^.*\.md$
      - id: end-of-file-fixer
        exclude: ^.*snapshots.*$
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: detect-private-key
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: check-merge-conflict
      - id: check-yaml
        name: Check YAML
        exclude: ^charts/|^helm/|^deploy/

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.10
    hooks:
      - id: uv-export
        args: ["--format", "requirements-txt", "--no-hashes", "--frozen", "--output-file", "requirements.txt", "--group", "types"]
        always_run: true

  - repo: https://github.com/GenessyX/validate-mypy-deps
    rev: v0.1.1
    hooks:
      - id: validate-mypy-deps
        always_run: true

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.19.1'  # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        args: [--strict]
        exclude: ^components/moneylift/proto/moneylift
        additional_dependencies:
          - anyio==4.9.0
          - casttube==0.2.1
          - certifi==2025.4.26
          - cffi==1.17.1
          - cfgv==3.5.0
          - charset-normalizer==3.4.1
          - click==8.1.8
          - colorama==0.4.6 ; sys_platform == 'win32'
          - distlib==0.4.0
          - filelock==3.24.3
          - granian==2.2.5
          - h11==0.16.0
          - identify==2.6.16
          - idna==3.10
          - ifaddr==0.2.0
          - librt==0.8.1 ; platform_python_implementation != 'PyPy'
          - mypy==1.19.1
          - mypy-extensions==1.1.0
          - nodeenv==1.10.0
          - pathspec==1.0.4
          - platformdirs==4.9.2
          - pre-commit==4.5.1
          - protobuf==6.30.2
          - pulsectl==24.11.0
          - pulsectl-asyncio==1.2.2
          - pychromecast==14.0.7
          - pycparser==2.22
          - pyyaml==6.0.3
          - requests==2.32.3
          - ruff==0.15.2
          - setuptools==80.1.0
          - sniffio==1.3.1
          - socketify==0.0.31
          - starlette==0.46.2
          - typed-ffmpeg==2.7.3
          - typing-extensions==4.13.2
          - urllib3==2.4.0
          - uvicorn==0.34.2
          - uvloop==0.21.0
          - virtualenv==20.38.0
          - zeroconf==0.146.5
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.20.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-angular']
